# Generated by Django 6.0.4 on 2026-05-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('budget_match_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('context', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_recommendations',
            },
        ),
        migrations.CreateModel(
            name='SearchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('normalized_query', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='foods', max_length=50)),
                ('result_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_events',
            },
        ),
    ]
