# Generated by Django 6.0.4 on 2026-05-03 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_models', '0001_initial'),
        ('nutrition', '0002_dailynutritionsummary_food_foodcategory_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='account',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='food',
            field=models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, to='nutrition.food'),
        ),
        migrations.AddField(
            model_name='searchevent',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.account'),
        ),
        migrations.AddField(
            model_name='searchevent',
            name='clicked_food',
            field=models.ForeignKey(blank=True, db_column='clicked_food_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_clicks', to='nutrition.food'),
        ),
    ]
