# Generated by Django 6.0.4 on 2026-05-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_models', '0002_add_ai_learning_admin_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlog',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='adminsetting',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='foodembedding',
            name='food',
        ),
        migrations.DeleteModel(
            name='IntentPattern',
        ),
        migrations.RemoveField(
            model_name='mealrecommendation',
            name='account',
        ),
        migrations.RemoveField(
            model_name='mealrecommendation',
            name='food',
        ),
        migrations.RemoveField(
            model_name='userfeedbackrecommendation',
            name='recommendation',
        ),
        migrations.DeleteModel(
            name='SystemMetric',
        ),
        migrations.RemoveField(
            model_name='userfeedbackfood',
            name='account',
        ),
        migrations.RemoveField(
            model_name='userfeedbackfood',
            name='food',
        ),
        migrations.RemoveField(
            model_name='userfeedbackrecommendation',
            name='account',
        ),
        migrations.RemoveField(
            model_name='userfeedbackrecommendation',
            name='food',
        ),
        migrations.DeleteModel(
            name='AdminLog',
        ),
        migrations.DeleteModel(
            name='AdminSetting',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='FoodEmbedding',
        ),
        migrations.DeleteModel(
            name='MealRecommendation',
        ),
        migrations.DeleteModel(
            name='UserFeedbackFood',
        ),
        migrations.DeleteModel(
            name='UserFeedbackRecommendation',
        ),
    ]
