# Generated by Django 6.0.5 on 2026-05-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_models', '0006_renumber_core_models_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='stt',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='stt',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='searchevent',
            name='clicked_food_stt',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
