# Generated by Django 6.0.5 on 2026-05-23 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_models', '0007_airecommendation_stt_mealrecommendation_stt_and_more'),
        ('nutrition', '0026_renumber_all_ids_sequential'),
        ('users', '0023_userfeedback_stt'),
    ]

    operations = []
