# Generated by Django 6.0.5 on 2026-05-23 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_models', '0007_airecommendation_stt_mealrecommendation_stt_and_more'),
        ('nutrition', '0026_renumber_all_ids_sequential'),
        ('users', '0023_userfeedback_stt'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(help_text='Intent type: recommendation, health, ingredient, budget', max_length=100)),
                ('pattern', models.TextField(help_text='Example: "tôi muốn giảm cân"')),
                ('confidence', models.FloatField(default=0.5, help_text='Pattern confidence')),
                ('created_by', models.CharField(choices=[('admin', 'Admin'), ('ai', 'AI'), ('user', 'User')], default='admin', max_length=50)),
                ('verified_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'intent_patterns',
            },
        ),
        migrations.CreateModel(
            name='MealRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.IntegerField(blank=True, db_index=True, null=True)),
                ('score', models.DecimalField(decimal_places=4, help_text='Overall score 0.0-1.0', max_digits=5)),
                ('match_score', models.DecimalField(blank=True, decimal_places=4, help_text='Taste match', max_digits=5, null=True)),
                ('budget_score', models.DecimalField(blank=True, decimal_places=4, help_text='Budget match', max_digits=5, null=True)),
                ('health_score', models.DecimalField(blank=True, decimal_places=4, help_text='Health match', max_digits=5, null=True)),
                ('reason', models.TextField(blank=True, help_text='Tại sao gợi ý')),
                ('ai_model_version', models.CharField(default='v1', help_text='Model version used', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_recommendations', to='users.account')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food')),
            ],
            options={
                'db_table': 'meal_recommendations',
            },
        ),
        migrations.CreateModel(
            name='UserFeedbackFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.IntegerField(blank=True, db_index=True, null=True)),
                ('rating', models.IntegerField(blank=True, help_text='1-5 stars', null=True)),
                ('is_liked', models.BooleanField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('feedback_type', models.CharField(choices=[('taste', 'Vị cảm'), ('health', 'Sức khỏe'), ('price', 'Giá cả'), ('convenience', 'Tiện lợi'), ('other', 'Khác')], default='taste', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_feedbacks', to='users.account')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food')),
            ],
            options={
                'db_table': 'user_feedback_food',
            },
        ),
        migrations.CreateModel(
            name='UserFeedbackRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.IntegerField(blank=True, db_index=True, null=True)),
                ('was_accepted', models.BooleanField(blank=True, help_text='Người dùng chấp nhận gợi ý', null=True)),
                ('was_helpful', models.BooleanField(blank=True, help_text='Gợi ý có hữu ích', null=True)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Thông tin về gợi ý')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedbacks', to='users.account')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_models.mealrecommendation')),
            ],
            options={
                'db_table': 'user_feedback_recommendation',
            },
        ),
        migrations.AddIndex(
            model_name='mealrecommendation',
            index=models.Index(fields=['account', '-score', 'created_at'], name='meal_recomm_account_946e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedbackfood',
            index=models.Index(fields=['account', 'food', 'created_at'], name='user_feedba_account_8f36ba_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedbackfood',
            index=models.Index(fields=['rating'], name='user_feedba_rating_1527f4_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedbackrecommendation',
            index=models.Index(fields=['account', 'was_accepted', 'was_helpful'], name='user_feedba_account_e64136_idx'),
        ),
        migrations.AddIndex(
            model_name='intentpattern',
            index=models.Index(fields=['intent', 'verified_by_admin'], name='intent_patt_intent_066d59_idx'),
        ),
    ]
