# Generated by Django 6.0.5 on 2026-06-12 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_models', '0008_restore_ai_learning_tables'),
        ('nutrition', '0026_renumber_all_ids_sequential'),
        ('users', '0023_userfeedback_stt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Experiment name (e.g., "personalization_v2")', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Experiment description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('control_variant', models.CharField(default='control', help_text='Control variant name', max_length=50)),
                ('test_variants', models.JSONField(default=list, help_text='List of test variant names: ["variant_a", "variant_b"]')),
                ('assignment_strategy', models.CharField(choices=[('hash', 'Hash-based (user_id % num_variants)'), ('random', 'Random assignment'), ('manual', 'Manual assignment')], default='hash', max_length=20)),
                ('traffic_allocation', models.IntegerField(default=100, help_text='Percentage of users to include (1-100)')),
                ('target_users', models.JSONField(blank=True, default=dict, help_text='User filters: {"min_id": 1, "max_id": 100}')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'experiments',
                'indexes': [models.Index(fields=['status', 'created_at'], name='experiments_status_b8c338_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExperimentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(help_text='Variant assigned to user', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core_models.experiment')),
            ],
            options={
                'db_table': 'experiment_assignments',
                'indexes': [models.Index(fields=['experiment', 'variant_name'], name='experiment__experim_a4b108_idx'), models.Index(fields=['account', 'experiment'], name='experiment__account_fb7f97_idx')],
                'unique_together': {('experiment', 'account')},
            },
        ),
        migrations.CreateModel(
            name='ExperimentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, help_text='recommendation_shown, recommendation_clicked, recommendation_rated', max_length=50)),
                ('variant_name', models.CharField(max_length=50)),
                ('value', models.FloatField(blank=True, help_text='Event value (e.g., rating score)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core_models.experiment')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.food')),
            ],
            options={
                'db_table': 'experiment_events',
                'indexes': [models.Index(fields=['experiment', 'event_type', 'variant_name'], name='experiment__experim_9616af_idx'), models.Index(fields=['account', 'experiment'], name='experiment__account_866118_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExperimentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(default='control', max_length=50)),
                ('metric_type', models.CharField(choices=[('click_through_rate', 'Click Through Rate'), ('conversion_rate', 'Conversion Rate'), ('avg_rating', 'Average Rating'), ('food_acceptance_rate', 'Food Acceptance Rate'), ('engagement_score', 'Engagement Score'), ('nutritional_match_score', 'Nutritional Match Score')], default='click_through_rate', max_length=50)),
                ('value', models.FloatField(default=0.0, help_text='Metric value')),
                ('count', models.IntegerField(default=1, help_text='Number of samples')),
                ('mean', models.FloatField(blank=True, null=True)),
                ('std_dev', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core_models.experiment')),
            ],
            options={
                'db_table': 'experiment_metrics',
                'indexes': [models.Index(fields=['experiment', 'variant_name'], name='experiment__experim_7eb130_idx'), models.Index(fields=['metric_type', 'recorded_at'], name='experiment__metric__cb34ba_idx')],
                'unique_together': {('experiment', 'variant_name', 'metric_type')},
            },
        ),
    ]
