# Generated by Django 6.0.5 on 2026-06-13 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_models', '0009_add_ab_testing_models'),
        ('users', '0023_userfeedback_stt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('query_text', models.TextField(blank=True)),
                ('normalized_query', models.TextField(blank=True)),
                ('intent_name', models.CharField(blank=True, max_length=100)),
                ('provider', models.CharField(choices=[('cache', 'Cache'), ('local_rule', 'Local rule'), ('local_llm', 'Local LLM'), ('gemini', 'Gemini'), ('fallback', 'Fallback')], db_index=True, max_length=50)),
                ('route_path', models.CharField(blank=True, db_index=True, max_length=50)),
                ('decision', models.CharField(blank=True, max_length=100)),
                ('ab_variant', models.CharField(blank=True, max_length=50)),
                ('cache_hit', models.BooleanField(db_index=True, default=False)),
                ('latency_ms', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('response_ok', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_logs', to='users.account')),
            ],
            options={
                'db_table': 'ai_request_logs',
                'indexes': [
                    models.Index(fields=['created_at', 'provider'], name='ai_request__created_165e59_idx'),
                    models.Index(fields=['provider', 'cache_hit', 'created_at'], name='ai_request__provide_891979_idx'),
                    models.Index(fields=['intent_name', 'created_at'], name='ai_request__intent__11a0f2_idx'),
                ],
            },
        ),
    ]
