# Generated by Django 6.0.6 on 2026-06-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_models', '0010_airequestlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='airequestlog',
            new_name='ai_request__created_804703_idx',
            old_name='ai_request__created_165e59_idx',
        ),
        migrations.RenameIndex(
            model_name='airequestlog',
            new_name='ai_request__provide_f5ccac_idx',
            old_name='ai_request__provide_891979_idx',
        ),
        migrations.RenameIndex(
            model_name='airequestlog',
            new_name='ai_request__intent__9e8eba_idx',
            old_name='ai_request__intent__11a0f2_idx',
        ),
    ]
