# Generated by Django 6.0.4 on 2026-05-03 15:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNutritionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('total_calories', models.FloatField(blank=True, null=True)),
                ('total_protein', models.FloatField(blank=True, null=True)),
                ('total_carbs', models.FloatField(blank=True, null=True)),
                ('total_fat', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_nutrition_summary',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('total_calories', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('total_protein', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('total_carbs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('total_fat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'foods',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'food_categories',
            },
        ),
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_grams', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'food_ingredients',
            },
        ),
        migrations.CreateModel(
            name='FoodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'food_tags',
            },
        ),
        migrations.CreateModel(
            name='FoodTagMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'food_tag_map',
            },
        ),
        migrations.CreateModel(
            name='IngredientPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_type', models.CharField(default='kg', max_length=20)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('source_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ingredient_prices',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='g', max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_items',
                'ordering': ['ingredient_name', 'expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='log_date')),
                ('meal_type', models.CharField(max_length=20)),
                ('servings', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nutrition_logs',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'food_recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_recipe_id', models.CharField(help_text='Recipe ID từ API (Spoonacular recipe_id hoặc TheMealDB idMeal)', max_length=100)),
                ('source_api', models.CharField(choices=[('spoonacular', 'Spoonacular'), ('themealdb', 'TheMealDB')], help_text='Nguồn recipe', max_length=20)),
                ('original_title', models.TextField(help_text='Tên recipe gốc (English)')),
                ('translated_title', models.TextField(blank=True, help_text='Tên recipe sau dịch (Tiếng Việt)', null=True)),
                ('translated_payload', models.JSONField(blank=True, help_text='Full recipe JSON sau dịch (title, instructions, ingredients, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recipe_translations',
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='g', max_length=50)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'shopping_items',
                'ordering': ['ingredient_name'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Danh sách mua sắm', max_length=200)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shopping_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(help_text='Text gốc (English)')),
                ('translated_text', models.TextField(help_text='Text sau dịch (Tiếng Việt)')),
                ('text_type', models.CharField(choices=[('instruction', 'Recipe Instruction'), ('ingredient_name', 'Ingredient Name'), ('ingredient_original', 'Ingredient Original'), ('summary', 'Recipe Summary'), ('title', 'Recipe Title'), ('other', 'Other')], default='other', help_text='Loại text được dịch', max_length=50)),
                ('source_context', models.CharField(blank=True, help_text='Context để trace (ví dụ: recipe_id=12345, food_id=789)', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'text_translations',
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(max_length=20)),
                ('to_unit', models.CharField(default='g', max_length=20)),
                ('conversion_factor', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'unit_conversions',
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
        migrations.RemoveField(
            model_name='ingredientnutrition',
            name='calcium',
        ),
        migrations.RemoveField(
            model_name='ingredientnutrition',
            name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='ingredientnutrition',
            name='iron',
        ),
        migrations.RemoveField(
            model_name='ingredientnutrition',
            name='raw_payload',
        ),
        migrations.RemoveField(
            model_name='ingredientnutrition',
            name='serving_size',
        ),
        migrations.RemoveField(
            model_name='ingredientnutrition',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='ingredientnutrition',
            name='source',
        ),
        migrations.RemoveField(
            model_name='ingredientnutrition',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='ingredientnutrition',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ingredientnutrition',
            name='vitamin_a',
        ),
        migrations.RemoveField(
            model_name='ingredientnutrition',
            name='vitamin_c',
        ),
        migrations.AlterField(
            model_name='ingredientalias',
            name='ingredient',
            field=models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='nutrition.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='fiber',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='ingredient',
            field=models.OneToOneField(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nutrition', serialize=False, to='nutrition.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
    ]
