# Generated by Django 6.0.4 on 2026-05-03 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_dailynutritionsummary_food_foodcategory_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynutritionsummary',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.account'),
        ),
        migrations.CreateModel(
            name='FoodDetail',
            fields=[
                ('food', models.OneToOneField(db_column='food_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='nutrition.food')),
                ('sugar', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('cholesterol', models.FloatField(blank=True, null=True)),
                ('vitamin_a', models.FloatField(blank=True, null=True)),
                ('vitamin_c', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('iron', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'food_details',
            },
        ),
        migrations.CreateModel(
            name='FoodEmbedding',
            fields=[
                ('food', models.OneToOneField(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nutrition.food')),
                ('embedding_vector', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'food_embeddings',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='nutrition.foodcategory'),
        ),
        migrations.AddField(
            model_name='foodingredient',
            name='food',
            field=models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, to='nutrition.food'),
        ),
        migrations.AddField(
            model_name='foodingredient',
            name='ingredient',
            field=models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, to='nutrition.ingredient'),
        ),
        migrations.AddField(
            model_name='foodtagmap',
            name='food',
            field=models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, to='nutrition.food'),
        ),
        migrations.AddField(
            model_name='foodtagmap',
            name='tag',
            field=models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='nutrition.foodtag'),
        ),
        migrations.AddField(
            model_name='ingredientprice',
            name='ingredient',
            field=models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, to='nutrition.ingredient'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='account',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='nutritionlog',
            name='account',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='nutritionlog',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='food',
            field=models.OneToOneField(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='nutrition.food'),
        ),
        migrations.AddIndex(
            model_name='recipetranslation',
            index=models.Index(fields=['source_api', 'source_recipe_id'], name='recipe_tran_source__4e6336_idx'),
        ),
        migrations.AddIndex(
            model_name='recipetranslation',
            index=models.Index(fields=['created_at'], name='recipe_tran_created_c95b2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipetranslation',
            unique_together={('source_api', 'source_recipe_id')},
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='account',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='shopping_list',
            field=models.ForeignKey(db_column='shopping_list_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.shoppinglist'),
        ),
        migrations.AddIndex(
            model_name='texttranslation',
            index=models.Index(fields=['original_text', 'text_type'], name='text_transl_origina_0fdb87_idx'),
        ),
        migrations.AddIndex(
            model_name='texttranslation',
            index=models.Index(fields=['created_at'], name='text_transl_created_b6149c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='texttranslation',
            unique_together={('original_text', 'text_type')},
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='ingredient',
            field=models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, to='nutrition.ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientalias',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ingredientalias',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ingredientalias',
            name='source',
        ),
        migrations.AlterUniqueTogether(
            name='foodingredient',
            unique_together={('food', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='foodtagmap',
            unique_together={('food', 'tag')},
        ),
    ]
