# Generated by Django 6.0.4 on 2026-05-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_dailynutritionsummary_account_fooddetail_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientalias',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='food',
            name='normalized_name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='total_calories',
        ),
        migrations.RemoveField(
            model_name='food',
            name='total_carbs',
        ),
        migrations.RemoveField(
            model_name='food',
            name='total_fat',
        ),
        migrations.RemoveField(
            model_name='food',
            name='total_protein',
        ),
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.DecimalField(blank=True, db_column='calories', decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='carbs',
            field=models.DecimalField(blank=True, db_column='carbs', decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.DecimalField(blank=True, db_column='fat', decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.DecimalField(blank=True, db_column='protein', decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
