# Generated by Django 6.0.4 on 2026-05-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0013_add_recipe_rating_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodverificationqueue',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodverificationqueue',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='foodverificationqueue',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='account',
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='recipe',
            new_name='food_recipe_auto_ad_bd12e6_idx',
            old_name='recipe_auto_rating_idx',
        ),
        migrations.RenameIndex(
            model_name='recipe',
            new_name='food_recipe_created_d69117_idx',
            old_name='recipe_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='reciperating',
            new_name='recipe_rati_recipe__beecdd_idx',
            old_name='rating_recipe_idx',
        ),
        migrations.RenameIndex(
            model_name='reciperating',
            new_name='recipe_rati_account_020262_idx',
            old_name='rating_account_idx',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='foodcategory',
                    name='created_at',
                ),
                migrations.RemoveField(
                    model_name='foodcategory',
                    name='description',
                ),
                migrations.RemoveField(
                    model_name='foodcategory',
                    name='icon',
                ),
                migrations.RemoveField(
                    model_name='foodcategory',
                    name='is_active',
                ),
                migrations.RemoveField(
                    model_name='foodcategory',
                    name='order_index',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='FoodVerificationQueue',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
