# Generated by Django 6.0.4 on 2026-05-04 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0014_remove_foodverificationqueue_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPopularity',
            fields=[
                ('food', models.OneToOneField(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nutrition.food')),
                ('view_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'food_popularity',
            },
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='date',
            field=models.TextField(),
        ),
    ]
