# Generated by Django 6.0.4 on 2026-05-05 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0015_foodpopularity_alter_nutritionlog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientprice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='ingredientprice',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='unitconversion',
            name='to_unit',
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='fiber',
            field=models.DecimalField(blank=True, db_column='fiber', decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='is_diabetes_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='is_weight_loss_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='search_vector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='nutrition.foodcategory'),
        ),
        migrations.AlterField(
            model_name='ingredientprice',
            name='unit_type',
            field=models.CharField(default='kg', max_length=50),
        ),
    ]
