# Generated by Django 6.0.4 on 2026-05-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0016_remove_ingredientprice_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.DecimalField(db_column='calories', decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.DecimalField(db_column='carbs', decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.DecimalField(db_column='fat', decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='fiber',
            field=models.DecimalField(db_column='fiber', decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(db_column='protein', decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name'], name='foods_name_01bd69_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['category_id'], name='foods_categor_3bb0f4_idx'),
        ),
    ]
