# Generated by Django 6.0.4 on 2026-05-06 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0022_remove_recipe_food_recipe_auto_ad_bd12e6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recipe',
            name='food_recipe_auto_ad_bd12e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='food_recipe_created_d69117_idx',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='foodingredient',
            name='quantity_grams',
            field=models.DecimalField(db_column='quantity', decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='food',
            field=models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, to='nutrition.food'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='meal_type',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='auto_added',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='total_ratings',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='updated_at',
        ),
    ]
