# Generated by Django 6.0.5 on 2026-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0023_remove_recipe_food_recipe_auto_ad_bd12e6_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in VND', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
