# Generated by Django 6.0.5 on 2026-05-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0024_alter_food_options_food_price_alter_foodcategory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
    ]
