# Generated by Django 5.2.13 on 2026-04-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_chatmessage',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('serving_size', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_diabetes_friendly', models.BooleanField(default=False)),
                ('is_weight_loss_friendly', models.BooleanField(default=False)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_food',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('health_goal', models.CharField(blank=True, max_length=200, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('dietary_preferences', models.TextField(blank=True, null=True)),
                ('activity_level', models.CharField(blank=True, max_length=50, null=True)),
                ('daily_calorie_target', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_userprofile',
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('meal_type', models.CharField(max_length=50)),
                ('servings', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.food')),
            ],
            options={
                'db_table': 'app_mealplan',
            },
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('meal_type', models.CharField(max_length=50)),
                ('servings', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('total_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_protein', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.food')),
            ],
            options={
                'db_table': 'app_nutritionlog',
            },
        ),
    ]
