# Generated by Django 6.0.4 on 2026-05-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.RemoveField(
            model_name='nutritionlog',
            name='food',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='NutritionLog',
        ),
    ]
