# Generated by Django 6.0.4 on 2026-05-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mealplan_add_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='food',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='account',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
