# Generated by Django 6.0.6 on 2026-06-27 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0006_add_stt_field'),
        ('users', '0023_userfeedback_stt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanDayFollow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('followed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
            options={
                'db_table': 'meal_plan_day_follows',
                'constraints': [models.UniqueConstraint(fields=('account', 'date'), name='uq_meal_plan_day_follow')],
            },
        ),
    ]
