from apps.chat.models import ChatMessage, ChatResponseCache, ChatSession, ChatSummary, Intent, IntentEmbedding, MessageIntent, Pattern
from apps.core_models.models import AIRecommendation, SearchEvent
from apps.core_models.ai_learning_models import AIRequestLog
from apps.meal_plans.models import MealPlan
from apps.nutrition.models import (
    DailyNutritionSummary,
    Food,
    FoodCategory,
    FoodIngredient,
    FoodPopularity,
    FoodTag,
    Ingredient,
    IngredientAlias,
    IngredientNutrition,
    IngredientPrice,
    Recipe,
    RecipeRating,
    ShoppingItem,
    ShoppingList,
    UnitConversion,
    NutritionLog,
)
from apps.users.models import (
    Account,
    Disease,
    DiseaseNutritionRule,
    UserBehaviorLog,
    UserBehaviorProfile,
    UserDisease,
    UserFeedback,
    UserGoal,
    UserPreferenceProfile,
    UserProfile,
)

__all__ = [
    'Account',
    'AIRecommendation',
    'AIRequestLog',
    'ChatMessage',
    'ChatResponseCache',
    'ChatSession',
    'ChatSummary',
    'DailyNutritionSummary',
    'Disease',
    'DiseaseNutritionRule',
    'Food',
    'FoodCategory',
    'FoodIngredient',
    'FoodPopularity',
    'FoodTag',
    'Ingredient',
    'IngredientAlias',
    'IngredientNutrition',
    'IngredientPrice',
    'Intent',
    'IntentEmbedding',
    'MealPlan',
    'MessageIntent',
    'NutritionLog',
    'Pattern',
    'Recipe',
    'RecipeRating',
    'SearchEvent',
    'ShoppingItem',
    'ShoppingList',
    'UnitConversion',
    'UserBehaviorLog',
    'UserBehaviorProfile',
    'UserDisease',
    'UserFeedback',
    'UserGoal',
    'UserPreferenceProfile',
    'UserProfile',
]
