# Generated by Django 6.0.4 on 2026-05-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_personalization_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhealthgoal',
            name='account',
        ),
        migrations.DeleteModel(
            name='UserBudget',
        ),
        migrations.DeleteModel(
            name='UserHealthGoal',
        ),
    ]
