# Generated by Django 6.0.4 on 2026-05-05 08:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userbehaviorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferenceProfile',
            fields=[
                ('account', models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.account')),
                ('preferred_macros', models.JSONField(blank=True, null=True)),
                ('preferred_categories', models.JSONField(blank=True, null=True)),
                ('preferred_keywords', models.JSONField(blank=True, null=True)),
                ('avoided_keywords', models.JSONField(blank=True, null=True)),
                ('healthy_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unhealthy_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_preference_profiles',
            },
        ),
        migrations.AddField(
            model_name='usergoal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='daily_calorie_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='goal_type',
            field=models.CharField(default='maintain', max_length=100),
        ),
        # Now we can set unique_together after goal_type field is added
        migrations.AlterUniqueTogether(
            name='usergoal',
            unique_together={('account', 'goal_type')},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.DeleteModel(
            name='UserBehaviorProfile',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='goal',
        ),
    ]
