# Generated by Django 6.0.4 on 2026-05-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_goal_and_budget'),
        ('users', '0016_alter_account_email_alter_account_role_and_more'),
    ]

    operations = [
    ]
