# Generated by Django 6.0.5 on 2026-05-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_renumber_users_app_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='stt',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
