# Generated by Django 6.0.4 on 2026-05-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_enhanced_chat_models'),
        ('users', '0013_remove_userhealthgoal_account_delete_userbudget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_fields', models.JSONField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'intents',
            },
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='account',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='intent_confidence',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='parsed_parameters',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='started_at',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_messages',
        ),
        migrations.AlterModelTable(
            name='chatsession',
            table='chat_sessions',
        ),
        migrations.CreateModel(
            name='ChatSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.chatsession')),
            ],
            options={
                'db_table': 'chat_summaries',
            },
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_fields', models.JSONField(blank=True, null=True)),
                ('ask_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_intent_id', models.IntegerField(blank=True, null=True)),
                ('filled_fields', models.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
            options={
                'db_table': 'conversation_states',
            },
        ),
        migrations.CreateModel(
            name='MessageIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('intent', models.ForeignKey(blank=True, db_column='intent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.intent')),
                ('message', models.ForeignKey(blank=True, db_column='message_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatmessage')),
            ],
            options={
                'db_table': 'message_intents',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('intent', models.ForeignKey(blank=True, db_column='intent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.intent')),
            ],
            options={
                'db_table': 'patterns',
            },
        ),
        migrations.CreateModel(
            name='ChatResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_query', models.TextField(help_text='Query sau khi normalize (lowercase, remove punct, lemmatize)')),
                ('original_query', models.TextField(help_text='Query gốc từ user')),
                ('gemini_response', models.TextField(help_text='Full response từ Gemini API')),
                ('source_intent', models.CharField(blank=True, help_text='Intent chính (ví dụ: ask_nutrition, meal_recommend)', max_length=100, null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Số lần response này được reuse từ cache')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Lần cuối cache được sử dụng (update khi reuse)', null=True)),
                ('account', models.ForeignKey(blank=True, db_column='account_id', help_text='NULL = guest chat, non-NULL = logged-in user', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
            options={
                'db_table': 'chat_response_caches',
                'indexes': [models.Index(fields=['normalized_query'], name='chat_respon_normali_7f7a62_idx'), models.Index(fields=['account', 'created_at'], name='chat_respon_account_98657b_idx'), models.Index(fields=['source_intent'], name='chat_respon_source__d69121_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('embedding_vector', models.JSONField()),
                ('source_type', models.CharField(choices=[('chat', 'Chat Message'), ('pattern', 'Pattern'), ('keyword', 'Intent Keyword')], default='chat', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(blank=True, db_column='message_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatmessage')),
                ('pattern', models.OneToOneField(blank=True, db_column='pattern_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.pattern')),
            ],
            options={
                'db_table': 'intent_embeddings',
                'indexes': [models.Index(fields=['intent_name', 'source_type'], name='intent_embe_intent__f8479d_idx'), models.Index(fields=['created_at'], name='intent_embe_created_98197d_idx')],
            },
        ),
    ]
