# Generated by Django 6.0.4 on 2026-05-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_merge_conversationstate_into_chatsession'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatresponsecache',
            name='chat_respon_account_98657b_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatresponsecache',
            name='chat_respon_source__d69121_idx',
        ),
        migrations.AddField(
            model_name='chatresponsecache',
            name='response',
            field=models.TextField(blank=True, help_text='Full response từ Gemini API', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chatresponsecache',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Số lần response này được reuse (metrics)'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='intent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='intent',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='chatresponsecache',
            index=models.Index(fields=['created_at'], name='chat_respon_created_fb5ac8_idx'),
        ),
        migrations.RemoveField(
            model_name='chatresponsecache',
            name='account',
        ),
        migrations.RemoveField(
            model_name='chatresponsecache',
            name='gemini_response',
        ),
        migrations.RemoveField(
            model_name='chatresponsecache',
            name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='chatresponsecache',
            name='source_intent',
        ),
    ]
