# Generated by Django 6.0.5 on 2026-06-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatresponsecache_intent_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatresponsecache',
            new_name='chat_respon_intent__0bf26f_idx',
            old_name='chat_respon_intent__77ccad_idx',
        ),
    ]
